name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Release Info
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "🎉 New alpha release published: ${{ steps.semantic.outputs.new_release_version }}"
          echo "Release channel: ${{ steps.semantic.outputs.new_release_channel }}"
          echo "Release notes:"
          echo "${{ steps.semantic.outputs.new_release_notes }}"
